joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50.0

# 滑动关节控制器（PD位置控制）
slide_joint_controller:
  type: effort_controllers/JointPositionController
  joint: slide_joint
  pid: {p: 100.0, i: 0.0, d: 10.0}

# 3个旋转关节控制器
joint1_controller:
  type: effort_controllers/JointPositionController
  joint: joint_1
  pid: {p: 100.0, i: 0.0, d: 10.0}

joint2_controller:
  type: effort_controllers/JointPositionController
  joint: joint_2
  pid: {p: 100.0, i: 0.0, d: 10.0}

joint3_controller:
  type: effort_controllers/JointPositionController
  joint: joint_3
  pid: {p: 100.0, i: 0.0, d: 10.0}